### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by paramminhas** [octoai/enterprise-dashboard#3]
[Octo-flow-Mock.pdf](https://github.com/octoai/enterprise-dashboard/files/373759/Octo-flow-Mock.pdf)

Use the library of your choice to explain the different functions and parts of the dashboard. Refer the pdf

**Comment by dipankar** [comment]
Please upload the PDF?

**Comment by ravingupta** [comment]
Using Javascript Library IntroJS for this and again its an onboarding process
